apiVersion: sources.knative.dev/v1alpha2
kind: SinkBinding
metadata:
  name: ce-producer-sink
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        app: ce-processing
  # any cloud event produced by our application will then be delivered to the Broker
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Broker
      name: default